(() => {
  const PINYIN_BY_CHAR = {
    '一': 'yi',
    '上': 'shang',
    '下': 'xia',
    '不': 'bu',
    '与': 'yu',
    '专': 'zhuan',
    '世': 'shi',
    '中': 'zhong',
    '主': 'zhu',
    '丽': 'li',
    '乐': 'le',
    '乖': 'guai',
    '书': 'shu',
    '事': 'shi',
    '二': 'er',
    '互': 'hu',
    '人': 'ren',
    '仙': 'xian',
    '代': 'dai',
    '伤': 'shang',
    '体': 'ti',
    '作': 'zuo',
    '侠': 'xia',
    '傲': 'ao',
    '儿': 'er',
    '先': 'xian',
    '光': 'guang',
    '公': 'gong',
    '关': 'guan',
    '兽': 'shou',
    '军': 'jun',
    '冷': 'leng',
    '几': 'ji',
    '创': 'chuang',
    '制': 'zhi',
    '前': 'qian',
    '办': 'ban',
    '力': 'li',
    '动': 'dong',
    '化': 'hua',
    '医': 'yi',
    '单': 'dan',
    '双': 'shuang',
    '受': 'shou',
    '古': 'gu',
    '合': 'he',
    '同': 'tong',
    '后': 'hou',
    '向': 'xiang',
    '味': 'wei',
    '和': 'he',
    '哨': 'shao',
    '哥': 'ge',
    '商': 'shang',
    '喜': 'xi',
    '回': 'hui',
    '园': 'yuan',
    '国': 'guo',
    '在': 'zai',
    '坏': 'huai',
    '基': 'ji',
    '士': 'shi',
    '外': 'wai',
    '多': 'duo',
    '大': 'da',
    '天': 'tian',
    '奇': 'qi',
    '女': 'nv',
    '奶': 'nai',
    '娇': 'jiao',
    '子': 'zi',
    '学': 'xue',
    '宅': 'zhai',
    '官': 'guan',
    '宝': 'bao',
    '室': 'shi',
    '家': 'jia',
    '富': 'fu',
    '少': 'shao',
    '尖': 'jian',
    '属': 'shu',
    '师': 'shi',
    '年': 'nian',
    '幻': 'huan',
    '弱': 'ruo',
    '强': 'qiang',
    '当': 'dang',
    '御': 'yu',
    '心': 'xin',
    '忠': 'zhong',
    '怪': 'guai',
    '情': 'qing',
    '想': 'xiang',
    '感': 'gan',
    '慢': 'man',
    '成': 'cheng',
    '战': 'zhan',
    '扮': 'ban',
    '攻': 'gong',
    '救': 'jiu',
    '文': 'wen',
    '族': 'zu',
    '日': 'ri',
    '明': 'ming',
    '星': 'xing',
    '暗': 'an',
    '替': 'ti',
    '最': 'zui',
    '月': 'yue',
    '末': 'mo',
    '材': 'cai',
    '校': 'xiao',
    '欢': 'huan',
    '正': 'zheng',
    '治': 'zhi',
    '法': 'fa',
    '泪': 'lei',
    '温': 'wen',
    '游': 'you',
    '灵': 'ling',
    '然': 'ran',
    '爱': 'ai',
    '父': 'fu',
    '特': 'te',
    '狂': 'kuang',
    '狐': 'hu',
    '现': 'xian',
    '甜': 'tian',
    '生': 'sheng',
    '电': 'dian',
    '男': 'nan',
    '病': 'bing',
    '百': 'bai',
    '的': 'de',
    '真': 'zhen',
    '着': 'zhe',
    '短': 'duan',
    '石': 'shi',
    '社': 'she',
    '神': 'shen',
    '禁': 'jin',
    '科': 'ke',
    '穿': 'chuan',
    '笨': 'ben',
    '等': 'deng',
    '系': 'xi',
    '纯': 'chun',
    '经': 'jing',
    '美': 'mei',
    '老': 'lao',
    '职': 'zhi',
    '能': 'neng',
    '自': 'zi',
    '舌': 'she',
    '色': 'se',
    '花': 'hua',
    '蛋': 'dan',
    '血': 'xue',
    '行': 'xing',
    '西': 'xi',
    '觉': 'jue',
    '角': 'jiao',
    '设': 'she',
    '豪': 'hao',
    '财': 'cai',
    '超': 'chao',
    '身': 'shen',
    '转': 'zhuan',
    '轻': 'qing',
    '近': 'jin',
    '逃': 'tao',
    '都': 'du',
    '重': 'chong',
    '金': 'jin',
    '钻': 'zuan',
    '长': 'chang',
    '间': 'jian',
    '阀': 'fa',
    '院': 'yuan',
    '霸': 'ba',
    '青': 'qing',
    '非': 'fei',
    '题': 'ti',
    '马': 'ma',
    '高': 'gao',
    '鱼': 'yu',
    '魔': 'mo',
    '黑': 'hei'
  };

  function normalizeText(value) {
    return String(value || '').normalize('NFKC').trim().toLowerCase();
  }

  function pinyinParts(value) {
    return Array.from(String(value || '')).map((char) => PINYIN_BY_CHAR[char] || normalizeText(char));
  }

  function buildIndex(value) {
    const normalized = normalizeText(value);
    const parts = pinyinParts(value).filter(Boolean);
    const full = parts.join('');
    const spaced = parts.join(' ');
    const initials = parts.map((part) => part[0] || '').join('');
    return [normalized, full, spaced, initials].filter(Boolean).join(' ');
  }

  function matches(value, query) {
    const normalizedQuery = normalizeText(query);
    return !normalizedQuery || buildIndex(value).includes(normalizedQuery);
  }

  window.TagSearch = { buildIndex, matches, normalizeText };
})();
