name = "novel-site-ver1"
pages_build_output_dir = "."
compatibility_date = "2026-02-01"

[[d1_databases]]
binding = "DB"
database_name = "novel-db"
database_id = "cbf11cb4-20b0-4744-b209-4dce704eff1e"

[[r2_buckets]]
binding = "R2"
bucket_name = "novel-storage"
